export const dict: Record<string, string> = {
  // フロントエンド
  react: "React",
  vue: "Vue.js",
  next: "Next.js",
  nuxt: "Nuxt.js",
  angular: "Angular",
  svelte: "Svelte",
  typescript: "TypeScript",
  javascript: "JavaScript",
  html: "HTML",
  css: "CSS",
  tailwind: "Tailwind CSS",
  bootstrap: "Bootstrap",
  jquery: "jQuery",

  // バックエンド
  node: "Node.js",
  express: "Express",
  nest: "NestJS",
  fastify: "Fastify",
  deno: "Deno",
  laravel: "Laravel",
  php: "PHP",
  ruby: "Ruby",
  rails: "Ruby on Rails",
  python: "Python",
  django: "Django",
  flask: "Flask",
  aspnet: "ASP.NET Core",
  csharp: "C#",
  java: "Java",
  spring: "Spring Boot",
  go: "Go",
  kotlin: "Kotlin",

  // データベース
  mysql: "MySQL",
  postgresql: "PostgreSQL",
  sqlite: "SQLite",
  mariadb: "MariaDB",
  mongodb: "MongoDB",
  redis: "Redis",
  oracle: "Oracle Database",
  sqlserver: "SQL Server",

  // インフラ・クラウド
  aws: "AWS",
  gcp: "Google Cloud Platform",
  azure: "Microsoft Azure",
  docker: "Docker",
  kubernetes: "Kubernetes",
  nginx: "Nginx",
  apache: "Apache",
  linux: "Linux",
  windowsserver: "Windows Server",

  // テスト・CI/CD
  jest: "Jest",
  testinglibrary: "React Testing Library",
  vitest: "Vitest",
  cypress: "Cypress",
  playwright: "Playwright",
  githubactions: "GitHub Actions",
  circleci: "CircleCI",

  // その他
  prisma: "Prisma",
  sequelize: "Sequelize",
  typeorm: "TypeORM",
  graphql: "GraphQL",
  rest: "REST API",
  storybook: "Storybook",
  electron: "Electron",
  vscode: "VSCode",
  figma: "Figma",
};
